# BASIC TENSORFLOW

# LOAD PACKAGES

In [1]:
import numpy as np
import tensorflow as tf
print ("PACKAGES LOADED")

PACKAGES LOADED


# SESSION

In [2]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


# TF CONSTANT

In [3]:
def print_tf(x):
    print("TYPE IS\n %s" % (type(x)))
    print("VALUE IS\n %s" % (x))
hello = tf.constant("HELLO. IT'S ME. ")
print_tf(hello)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const:0", shape=(), dtype=string)


# TO MAKE THINKS HAPPEN

In [4]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS
 <class 'bytes'>
VALUE IS
 b"HELLO. IT'S ME. "


# OTHER TYPES OF CONSTANTS

In [5]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_1:0", shape=(), dtype=float32)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_2:0", shape=(), dtype=float32)


In [6]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 2.5


# OPERATORS

In [7]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Add:0", shape=(), dtype=float32)


In [8]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 4.0


In [11]:
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 3.75


# VARIABLES

In [13]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

Instructions for updating:
Colocations handled automatically by placer.
TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [14]:
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}}]]

# WHY DOES THIS ERROR OCCURS?

In [15]:
init = tf.initialize_all_variables()
sess.run(init)
print ("INITIALIZING ALL VARIALBES")

Instructions for updating:
Use `tf.global_variables_initializer` instead.
INITIALIZING ALL VARIALBES


# ONCE, WE INITIALIZE VARIABLES

In [16]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.20427556  0.09444238]
 [ 0.00421372 -0.19508879]
 [-0.06402701 -0.12925802]
 [ 0.0772147   0.10808825]
 [ 0.15042011  0.12291016]]


# PLACEHOLDERS

In [17]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


## OPERATION WITH VARIABLES AND PLACEHOLDERS

In [18]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [19]:
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.0350525  -0.07292104]]


In [20]:
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.02941397 -0.14243914]
 [ 0.00133212 -0.03689558]]
